apiVersion: v1
kind: Service
metadata:
  name: fluentd-logger
  labels:
    app: fluentd-logger
spec:
  type: ClusterIP
  selector:
    app: fluentd-logger
  ports:
  - name: fluentd
    port: 9880
    targetPort: 9880
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fluentd-logger
  labels:
    app: fluentd-logger
spec:
  to:
    kind: Service
    name: fluentd-logger
    weight: 100
  port:
    targetPort: 9880
  wildcardPolicy: None
  


