apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
commonLabels: 
   app: fluent-logger
resources: 
   - ./fluentd-cm.yaml 
   - ./nginx-cm.yaml 
   - ./fluentd-service.yaml 
   - ./nginx-service.yaml 
   - ./deployment.yaml 
   